BurntSushi/fst

Cargo.toml
src/lib.rs
src/map.rs
src/raw/mod.rs
src/set.rs

Allows to disable memmap dependency when no filesystem is avaible.
(required to build for wasm/asmjs)

added mmap feature (default on). 

---

src/map.rs
src/raw/build.rs
src/raw/counting_writer.rs
src/raw/tests.rs
src/set.rs

Feedback welcome!
While the `get_ref()` code is fairly simple, I would still like to write a test. Any ideas how to that while keeping the borrow checker happy?
I also don't like the magic footer size constant in the `bytes_written` test, but haven't found a decent way around that.
I omitted a `get_mut` implementation, because IMHO this might be a bit of a footgun, allowing corruption of the fst stream.

add get_ref(), bytes_written() to MapBuilder (#23)

---

README.md

This is the latest version of the fst crate, and is what is mentioned in the next paragraph.

Updates README Cargo.toml example to say 0.3.0

---

src/map.rs
src/set.rs
tests/test.rs

What do you think about adding `Default` for map & set?
On the one hand, `Default` does not really make sense, because fsts are immutable once created. On the other hand, the APIs which use two-phase construction exist (i.e, the recent PR to rls-analysis), and for them having a default is handy.

Implement `Default` for Set and Map

---

.travis.yml
Cargo.toml
appveyor.yml
ci/script.sh
fst-levenshtein/Cargo.toml
fst-regex/Cargo.toml

We retain our minimum Rust version of 1.20.0, but we now only test the
crate on stable/beta/nightly (we only ensure it builds on Rust 1.20.0).

deps: update various dependencies

---

src/automaton/mod.rs

This PR propose to add Clone and Debug traits using the derive syntax on the native automatons.
These traits was already implemented [by `SubSequence`](https://github.com/BurntSushi/fst/blob/ccd50804450fe347130c704d84868cdf878d52e8/src/automaton/mod.rs#L150).
I find this useful in some of my usages.
These additions doesn't introduce breaking changes to the library.

Implement Clone and Debug on automatons

---

fst-levenshtein/src/lib.rs
fst-regex/src/error.rs
fst-regex/src/lib.rs
src/automaton/mod.rs
src/error.rs
src/map.rs
src/raw/build.rs
src/raw/error.rs
src/raw/mmap.rs
src/raw/mod.rs
src/raw/node.rs
src/raw/ops.rs
src/set.rs

Without link-time optimization, Rust cannot inline non-generic functions across crate boundary.
This patch adds `#[inline]` annotation to trivial public non-generic functions so that Rust can inline them on callsites.

add #[inline] to public non-generic functions

---

src/raw/mod.rs

Just fixing mardown.
(The image didn't show on docs.rs, because of the newline).

doc: Make the image of billion strings appear

---

src/map.rs
src/raw/ops.rs

Reading the docs previously was a bit confusing ‒ while the nature of
the operation hints at exactly one IndexValue, the interface hints at
arbitrary number and the docs kind of did too and one has to wonder what
the trick is. Pointing it out explicitly should prevent the latter.

docs: Explicitly point out than difference has 1 IndexValue

---

src/raw/mod.rs

Similar to .to_vec(), but without making copies.
* Currently, I'm keeping a map in memory and exchange it from time to time. Later on I'd like to store it to a cache (but not at the time when I'm constructing it) and currently I have to use the `to_vec` and then `write_all` ‒ which is wasteful, because it creates a copy of the whole thing in memory.
* For some metrics I'd like to know the size of the image (not .len() ‒ that one is number of keys). Calling `to_vec` for that is obviously too wasteful.
If this change is OK, would it be fine to have a release with it?
Thank you

Raw fst .as_bytes()

---

src/map.rs
src/set.rs

Intended usage is as shown in the documentation examples:
```rust
use fst::Set;
// File written from a build script using SetBuilder.
static FST: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/set.fst"));
let set = Set::from_static_slice(FST).unwrap();
```
This would have been useful in https://github.com/derekdreery/common-passwords/pull/1.

Add Set/Map::from_static_slice

---

src/automaton/mod.rs
tests/test.rs

This adds ability to match exact strings against the given set, as well as enables trie usecase by combining it with `StartsWith<_>`.
Name is subject to change, I don't have strong preferences either way, as well as would be happy with just implementing `Automaton` directly on `str` / `[u8]` (which seems to make sense).

Add `fst::Str` automaton for exact strings

---

src/map.rs
src/set.rs

This PR propose to add a convenient method on the `Set` and `Map` builders to directly create a `Set` or `Map` from the builder itself.
The advantage here is to reduce the number of unwraps necessary to create a `Set`/`Map` from a `Set`/`MapBuilder` based on a _known valid_ `Vec<u8>`.
```rust
let mut build = MapBuilder::memory();
build.insert("bruce", 1).unwrap();
build.insert("clarence", 2).unwrap();
build.insert("stevie", 3).unwrap();
// current way of constructing a known valid map from a builder
let bytes = build.into_inner().unwrap();
let map = Map::from_bytes(bytes).unwrap();
// could also be written as
let map = build.into_inner().and_then(Map::from_bytes).unwrap();
// new way (no more useless unwraps)
let map = build.into_map();
```

Introduce a convenient method to create an fst from a builder

---

src/lib.rs
src/raw/mod.rs

This removes `This example is not tested` warnings on `docs.rs`.

replace `ignore` with  `plain` for non code docs

---

src/raw/mod.rs

I think there is a missing method on the Fst to retrieve the underlying Data type.
I need this method to transform a Set based on a `&[u8]` into a Set based on a `Cow`, owned and borrowed on demand.

Introduce a method to retrieve the inner data of an Fst

---

src/automaton/mod.rs
src/raw/mod.rs

This is to support automata that delay matches by one byte. (Which is
what regex-automata will do in its 0.2 release, in order to support
look-around assertions such as ^, $ and \b.)
This requires a small tweak to the search code to call this new method
once it sees a final node.
This is *not* a breaking change. Existing implementations continue to
work since the default implementation of `accept_eof` (returning None)
is always correct for automata that do not delay matches.

automaton: add new accept_eof method

---

src/map.rs
src/raw/mod.rs
src/set.rs

I would like to introduce the new `into_fst` method to the `Set` and `Map` types.
This method consumes the wrapper types and extracted the underlying raw fst, this enables many possiblities and fixes an issue I found with #102.
1. We can change the way we want to read an fst by extracting the underlying fst of a wrapper like a Set and construct a Map from it for example (I need this in one of my libraries, this is not just a fun feature).
2. This also fixes the issue of #102 which introduced an `into_inner` method to extract the data of a raw fst. Because the only way to get the underlying fst of a Set or a Map  was by reference using the `as_fst` method it wasn't possible to reuse the extracted `Data` and map it into another type. The original goal of #102 was to transform the data of a …

Introduce the Set and Map into_fst method

---

src/map.rs
src/raw/mod.rs
src/set.rs

This method is implemented on the `fst::Map/Set` and `raw::Fst` types, it allows to change the underlying data type without having to deconstruct the type by hand. This can be especially usefull when an fst `Map` or `Set` is based on another type than a `Vec` and you need a default value for that type, you can call default and map it to the right data type you need (e.g. `Arc`, `Rc`, `Cow`) on a single line.
```rust
use std::borrow::Cow;
use std::sync::Arc;
use fst::Map;
// Can be used with Cows
let iter = [("hello", 12), ("world", 42)].iter().cloned();
let map: Map<Vec<u8>> = Map::from_iter(iter)?;
let map_on_cow: Map<Cow<[u8]>> = map.map_data(Cow::Owned)?;
// Or even be used with Arcs
let map: Map<Vec<u8>> = Map::default();
let map_on_arc: Map<Arc<[u8]>> = map.map_data(Arc::from)?;
``` …

Introduce a map_data method

---

src/raw/mod.rs

Add Fst::as_inner to give temporary access to underlying data

---

src/map.rs

The doc was mentioning duplicate values when discussing duplicate values
of keys. Since in a map doc there are already discussion of keys mapped
to values it might be better to avoid possible confusion there.
Therefore always use keys when talking about keys.
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

Clarify doc on duplicate map keys

---

src/raw/mod.rs

I was going over the docs and noticed the related FST diagrams don't actually contain these strings.

Remove "apr" from examples

---

src/raw/mod.rs

Correction in output sub function comment.
Currently reads:
/// This function panics if `self > o`.
However from looking at the code, self should always be greater than or equal to o.
So the correct direction should be:
/// This function panics if `self < o`.

Update mod.rs. Correction in output sub function comment.
